pofolduce201/src/main/resources/static/css/banner.css
pofolduce201/src/main/resources/templates/index.html

fix: 배너 css 수정

---

pofolduce201/src/main/resources/templates/fragments/html/board-header.html

이전에 board-header의 내용이 고정되어 동적으로 변경 불가능 했던 것을 동적으로 내용을 입력할 수 있게 수정
#10 board-header 내용 동적으로 변경 가능하게 수정
closed #10 
- board-header.html의 코드를 수정
th:text=${boardName}을 사용하여 입력 받은 값을 표시할 수 있게 수정
서버 실행하여 변경한 값이 잘 나오는 것을 확인
- 사진 첨부

fix : 컴포넌트 board-header의 내용을 동적으로 바꿀 수 있도록 수정

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/ReviewBoardController.java
pofolduce201/src/main/java/org/kosa/_musketeers/domain/ReviewPostComment.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/ReviewBoardMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/ReviewBoardService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/ReviewBoardMapper.xml
pofolduce201/src/main/resources/templates/pages/review/review-post.html

첨삭 게시판의 게시물에서 댓글을 작성하고, 조회하고, 삭제할 수 있도록 구현하였습니다.
#38 첨삭게시판
댓글을 작성할 수 있는 기능 구현
댓글을 삭제할 수 있는 기능 구현
댓글을 조회할 수 있도록 구현
댓글 수정은 구현에 실패하였습니다.
단위 테스트 생략 후 서버 가동하여 구동 확인했습니다.
- 사진 첨부

feat : 리뷰게시판 댓글 등록, 조회, 삭제 구현

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/StudyBoardRestController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/UserController.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/ReviewBoardMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/UserMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/ReviewBoardService.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/UserService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/ReviewBoardMapper.xml
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/UserMapper.xml
pofolduce201/src/main/resources/templates/pages/mypage/userpage.html
pofolduce201/src/main/resources/templates/pages/study/study-board-post.html

다른 유저 닉네임 클릭시 팝오버가 뜨고 팝오버에서 상세 페이지로 가는 버튼과 다른 유저 상세 페이지 구현
- 다른 유저 닉네임 클릭시 팝오버
- 팝오버에서 상세 페이지로 가는 버튼
-다른 유저 상세 페이지 구현
- 사진 첨부

feat: 다른 유저 페이지

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/ReviewBoardController.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/ReviewBoardService.java
pofolduce201/src/main/resources/templates/pages/review/review-select-folio-confirm.html
pofolduce201/src/main/resources/templates/pages/review/review-select-folio.html

리뷰 게시판 글 작성시 이력서 추가 팝업 구현
#33 리뷰 게시판
이력서 추가 버튼에 onclick 추가, 자바스크립트 함수 추가
이후 Ajax 사용하여 이력서 pdf HTML변환 문자열 텍스트 에디터에 추가
- 사진 첨부

feat : 첨삭 게시물 작성에 이력서 추가 버튼 팝업 추가

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/StudyBoardController.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/StudyBoardMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/StudyBoardService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/StudyBoardMapper.xml
pofolduce201/src/main/resources/static/css/popover.css
pofolduce201/src/main/resources/templates/pages/study/study-board.html

스터디 조회수 및 스터디 게시판 수정
- 스터디 게시글 조회시 조회수가 안 올라가는 것을 수정
- 게시판의 컬럼 변경
- 사진 첨부

fix: 스터디 조회수 및 스터디 게시판 수정

---

pofolduce201/src/main/java/org/kosa/_musketeers/service/RecruitService.java

채용 공고 list 크기를 넘어버리는 현상 수정
- 채용 공고 오류 임시 수정입니다.
- 사진 첨부

fix : 채용 공고 list 크기를 넘어버리는 현상 수정

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/StudyBoardController.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/StudyBoardMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/StudyBoardService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/StudyBoardMapper.xml
pofolduce201/src/main/resources/static/css/study-css/study-board.css
pofolduce201/src/main/resources/templates/fragments/html/report-modal.html
pofolduce201/src/main/resources/templates/pages/study/study-board-post.html
pofolduce201/src/main/resources/templates/pages/study/study-board.html

map에 마커와 마커 클릭시 게시글로 이동 기능 구현
- 게시판에 전체 마커 추가
- 게시판 마커 클릭시 해당 게시글로 이동
- 게시글에 각각 지도 마커 추가
- 사진 첨부

feat: map에 마커와 마커 클릭시 게시글로 이동 기능 구현

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/ReviewBoardController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/ReviewController.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/ReviewMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/ReviewService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/ReviewMapper.xml
pofolduce201/src/main/resources/static/js/review-post.js

첨삭 업데이트를 구현하였습니다.
#33 
- 첨삭의 수정 버튼을 누르면 수정 창이 생깁니다. 
- 취소를 누르면 수정 창이 사라집니다.(javascriptonclick 사용, 이후 수정할 수 있음)
- 완료 버튼을 누르면 서버에 업데이트되고, 리뷰를 리로드합니다. (button, click eventListner 사용, ajax를 통한 비동기 통신)
서버에서 테스트
- 사진 첨부

feat : 첨삭 업데이트 구현

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/HomeController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/RecruitController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/SearchController.java
pofolduce201/src/main/java/org/kosa/_musketeers/domain/ReviewPost.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/ReviewBoardMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/UserMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/RecruitService.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/ReviewBoardService.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/StudyBoardService.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/UserService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/RecruitMapper.xml
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/ReviewBoardMapper.xml
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/UserMapper.xml
pofolduce201/src/main/resources/static/css/page-css/home.css
pofolduce201/src/main/resources/static/js/home.js
pofolduce201/src/main/resources/templates/pages/home/home.html
pofolduce201/src/main/resources/templates/pages/search/search-recruit.html
pofolduce201/src/main/resources/templates/pages/search/search.html

메인 화면에 게시글이 올라오도록 구현
#30 
- 메인 화면에 게시글이 올라오도록 구현했습니다.
- 채용 공고 검색 가능하도록 구현했습니다.
- 사진 첨부

feat : 메인 화면에 게시글이 올라오도록 구현 및 채용 공고 검색 구현

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/SearchController.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/UserMapper.xml
pofolduce201/src/main/resources/static/css/page-css/search.css
pofolduce201/src/main/resources/templates/pages/home/home.html
pofolduce201/src/main/resources/templates/pages/search/search-recruit.html
pofolduce201/src/main/resources/templates/pages/search/search-review.html
pofolduce201/src/main/resources/templates/pages/search/search-study.html
pofolduce201/src/main/resources/templates/pages/search/search.html

채용 공고 검색, 이력서 검색 구현
#31 
close #31 
- 이력서 검색 시 전체 검색 결과에서 캐러셀로 나타내도록 구현했습니다.
- 채용 공고를 검색할 수 있습니다.
- 사진 첨부

feat : 채용 공고 검색, 이력서 검색 구현

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/UserController.java
pofolduce201/src/main/java/org/kosa/_musketeers/domain/Verification.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/UserMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/MyBoardService.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/UserService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/MyBoardMapper.xml
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/UserMapper.xml
pofolduce201/src/main/resources/static/css/page-css/mypage-main.css
pofolduce201/src/main/resources/static/js/mypage.js
pofolduce201/src/main/resources/templates/pages/mypage/mypage-main.html
pofolduce201/src/main/resources/templates/pages/mypage/mypage-mycomment.html
pofolduce201/src/main/resources/templates/pages/mypage/mypage-myreview.html
pofolduce201/src/main/resources/templates/pages/search/search-review.html

유저가 회사 인증을 할 수 있는 기능 구현
#63 
close #63 
- 유저가 회사 인증을 할 수 있는 기능 구현
- 경로변경에 따른 url 변경 및 vo 변경으로 인한 조회 수정사항 반영
- 마이페이지 내 게시글 조회 시 속도가 느려지는 현상 수정

feat : 유저가 회사 인증을 할 수 있는 기능 구현

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/NoticeBoardController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/RankingController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/RecruitController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/ReviewBoardController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/StudyBoardController.java
pofolduce201/src/main/resources/static/css/header1.css
pofolduce201/src/main/resources/static/css/header2.css
pofolduce201/src/main/resources/static/css/review-css/review-board.css
pofolduce201/src/main/resources/templates/fragments/html/header1.html
pofolduce201/src/main/resources/templates/fragments/html/header2.html
pofolduce201/src/main/resources/templates/layouts/layout.html
pofolduce201/src/main/resources/templates/pages/notice/notice-board.html
pofolduce201/src/main/resources/templates/pages/review/review-post-board.html
pofolduce201/src/main/resources/templates/pages/study/study-board.html

충돌 해결 및 css 수정
- 충돌 해결
- css 수정
- header 추가
- 컨트롤러들에 httpservletrequest 추가
- 사진 첨부

fix: 충돌 해결 및 css 수정

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/ReportController.java
pofolduce201/src/main/resources/templates/fragments/html/review-post-report-modal.html
pofolduce201/src/main/resources/templates/pages/review/review-post.html

첨삭 게시판 user popover, 신고 기능 추가
#33 
- reportController 에 reportReviewBoard 메서드 추가, 첨삭게시판 신고 담당
- reportModal 추가
- user Popover 추가
- 작업 2
단위 테스트 생략
서버 실행하여 작동 확인
- 사진 첨부

feat : 첨삭 게시판 user popover, 신고 기능 추가

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/AdminUserController.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/UserMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/UserService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/AdminMapper.xml
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/UserMapper.xml
pofolduce201/src/main/resources/templates/pages/admin/admin-certificationpage.html

- 회사 인증 페이지에서 닉네임 추가
- 회사 인증 페이지에 완료, 반려 되었을때 클릭시 버튼 없애고 메세지 띄우기
- 완료, 반려를 했을때 유저 페이지로 이동하면 반려, 완료, 회사 명 띄우기
- 작업 1
- 작업 2
- 사진 첨부

feat : 회사 인증 페이지 수정 및 유저정보 페이지 수정

---

pofolduce201/src/main/resources/static/css/notice-css/notice-board-post.css
pofolduce201/src/main/resources/static/css/review-css/review-post-write.css
pofolduce201/src/main/resources/static/css/review-css/review-post.css
pofolduce201/src/main/resources/static/js/review-post.js
pofolduce201/src/main/resources/templates/layouts/layout.html
pofolduce201/src/main/resources/templates/pages/notice/notice-post-create.html
pofolduce201/src/main/resources/templates/pages/notice/notice-post-update.html
pofolduce201/src/main/resources/templates/pages/review/review-post-edit.html
pofolduce201/src/main/resources/templates/pages/review/review-post-write.html
pofolduce201/src/main/resources/templates/pages/review/review-post.html
pofolduce201/src/main/resources/templates/pages/study/study-board-post.html

게시판 css 통합
- 첨삭 게시판 css 수정
- 공지사항 게시판 css 수정
- 사진 첨부

fix: 게시판 css 통합

---

pofolduce201/src/main/java/org/kosa/_musketeers/Pofolduce201Application.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/HomeController.java
pofolduce201/src/main/java/org/kosa/_musketeers/mapper/RecruitMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/RecruitService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/RecruitMapper.xml
pofolduce201/src/main/resources/static/css/signup-css/login.css
pofolduce201/src/main/resources/static/css/signup-css/signup.css
pofolduce201/src/main/resources/templates/pages/login/login.html
pofolduce201/src/main/resources/templates/pages/signup/createaccount.html

크롤링 주기 설정 및 로그인/회원가입 페이지 CSS 추가
- 스케줄링 추가로 5분마다 DB 제거 후 채용 공고를 긁어오도록 설정
- 로그인 CSS 수정
- 회원 가입 CSS 수정
- 사진 첨부

feat : 크롤링 주기 설정 및 로그인/회원가입 페이지 CSS 추가

---

pofolduce201/src/main/java/org/kosa/_musketeers/config/WebConfig.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/StudyBoardController.java
pofolduce201/src/main/java/org/kosa/_musketeers/domain/Portfolio.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/UserService.java
pofolduce201/src/main/resources/templates/pages/study/study-board-update.html
pofolduce201/src/main/resources/templates/pages/study/study-board-write.html

이력서 업로드하는 파일 위치 외부 파일로 수정
- 이력서 업로드하는 파일 위치 외부 파일로 수정
- 사진 첨부

fix: 이력서 업로드하는 파일 위치 외부 파일로 수정

---

pofolduce201/src/main/java/org/kosa/_musketeers/mapper/UserMapper.java
pofolduce201/src/main/java/org/kosa/_musketeers/runner/CreateAdmin.java
pofolduce201/src/main/java/org/kosa/_musketeers/scheduler/RecruitScheduler.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/UserMapper.xml

서버 처음 실행 시 관리자 계정을 추가하도록 설정
- 서버 처음 실행 시 관리자 계정을 추가하도록 설정

feat : 서버 처음 실행 시 관리자 계정을 추가하도록 설정

---

pofolduce201/src/main/java/org/kosa/_musketeers/domain/Portfolio.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/UserService.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/PortfolioMapper.xml
pofolduce201/src/main/resources/templates/pages/mypage/mypage-myportfolio-detail.html
pofolduce201/src/main/resources/templates/pages/mypage/mypage-myportfolio.html

이력서 외부폴더 수정
- 이력서 외부폴더 수정
- 사진 첨부

fix: 이력서 외부폴더 수정

---

pofolduce201/src/main/java/org/kosa/_musketeers/config/WebConfig.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/AdminUserController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/UserController.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/UserService.java

fix : 파일 경로 수정

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/AdminUserController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/NoticeBoardController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/ReviewController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/SearchController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/UserController.java
pofolduce201/src/main/java/org/kosa/_musketeers/scheduler/RecruitScheduler.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/RecruitService.java

불필요한 코드 삭제
- 불필요한 코드 삭제
- 사진 첨부

chore: 불필요한 코드 삭제

---

pofolduce201/src/main/java/org/kosa/_musketeers/config/WebConfig.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/ReviewBoardService.java
pofolduce201/src/main/java/org/kosa/_musketeers/service/UserService.java
pofolduce201/src/main/resources/static/js/review-post.js
pofolduce201/src/main/resources/templates/pages/review/review-post.html

이미지, pdf 등 파일 외부 폴더 사용으로 인한 오류 수정
- addResourceHandler 주소 수정
-  UserService 이미지 업로드 주소 수정
- 사진 첨부

fix : 외부 폴더 사용으로 인한 오류 수정

---

pofolduce201/src/main/java/org/kosa/_musketeers/controller/HomeController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/RecruitController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/SearchController.java
pofolduce201/src/main/java/org/kosa/_musketeers/controller/UserController.java
pofolduce201/src/main/resources/org/kosa/_musketeers/mapper/ReviewBoardMapper.xml
pofolduce201/src/main/resources/templates/pages/admin/admin-report.html
pofolduce201/src/main/resources/templates/pages/admin/admin-reportpage.html

빌드 후 발견된 오류 수정
- 첨삭 게시판 좋아요 올라가지 않는 문제 해결
- 주소가 잘못되어 페이지가 나오지 않는 오류 수정
- iframe 크기가 작아 화면 깨지는 부분 수정
빌드 테스트
- 사진 첨부

fix :  build test에서 발견된 문제점 수정
